# Usar uma imagem base Python
FROM python:3.9-slim

# Definir o diretório de trabalho no contêiner
WORKDIR /app

# Copiar os arquivos necessários para o diretório de trabalho
COPY requirements.txt requirements.txt
COPY app.py app.py

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta que o Flask usará
# EXPOSE 5000

# Comando para rodar a aplicação
CMD ["python", "app.py"]